//
//  MovieDetailPresenter.swift
//  TheMovieDbApp
//
//  Created by HalitG on 7.03.2021.
//  Copyright (c) 2021 HalitG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic
{
    func presentMovie(movie: Movie, selectedMovieIndex: Int)
}

class MovieDetailPresenter: MovieDetailPresentationLogic
{
    weak var viewController: MovieDetailDisplayLogic?
    
    func presentMovie(movie: Movie, selectedMovieIndex: Int)
    {
        viewController?.load(movie: movie, selectedMovieIndex: selectedMovieIndex)
    }
}
