//
//  MovieListRouter.swift
//  TheMovieDbApp
//
//  Created by HalitG on 7.03.2021.
//  Copyright (c) 2021 HalitG. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListRoutingLogic
{
    func routeToMovieDetail(movie: Movie, index: Int)
}

protocol MovieListDataPassing
{
    var dataStore: MovieListDataStore? { get }
}

class MovieListRouter: NSObject, MovieListRoutingLogic, MovieListDataPassing
{
    weak var viewController: MovieListViewController?
    var dataStore: MovieListDataStore?
    
    // MARK: Routing
    
    func routeToMovieDetail(movie: Movie, index: Int) {
        let storyboard = UIStoryboard(name: "MovieDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MovieDetailViewController") as! MovieDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationDS.selectedMovie = movie
        destinationDS.selectedMovieIndex = index
        
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    private func navigateToSomewhere(source: MovieListViewController, destination: MovieDetailViewController)
    {
        source.show(destination, sender: nil)
    }
}
